public class TokenResponse {
    public String access_token;
    public String id_token;
    public String refresh_token;
    public Integer expires_in;
    public Integer refresh_token_expires_in;
    public String token_type;
    public String usid;
    public String customer_id;
    public String enc_user_id;
    public String idp_access_token;
    public String idp_refresh_token;
    public String status_code;
}